apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec: 
  ports:
  - port: 80
    targetPort: 3500  # Ensure this matches the port your container is listening on
    protocol: TCP
  type: LoadBalancer   # Change ClusterIP to LoadBalancer
  selector:
    role: api
