FROM node:14
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
CMD ["npm", "start", "--", "--host", "0.0.0.0"]





# apiVersion: v1
# kind: Service
# metadata: 
#   name: frontend
#   namespace: three-tier
# spec:
#   ports:
#   - port: 3000
#     protocol: TCP
#   type: ClusterIP
#   selector:
#     role: frontend
