apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
spec:
  type: LoadBalancer
  selector:
    role: frontend # Match the "role" label from Deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
